.TH PMENU 1
.SH NAME
pmenu \- pie menu utility for X
.SH SYNOPSIS
.B pmenu
.RB [ \-w ]
[(\fB\-x\fP|\fB\-X\fP) [\fImod\fP-]\fIbutton\fP]
.SH DESCRIPTION
.B pmenu
is a pie menu for X,
it reads a list of newline-separated items from stdin,
shows a pie menu for the user to select one of the items,
and outputs the item selected to stdout.
The pie menu contains one slice for each item.
.PP
The options are as follows:
.TP
.B \-w
Disable pointer warping when a new submenu spawns.
This option is useful when using
.B pmenu
with a Wacom tablet.
.TP
\fB\-x\fP [\fImod\fP-]\fIbutton\fP
This option requires an argument of the form
\fImod\fP-\fIbutton\fP or \fIbutton\fP; where
.I mod
is
.B Mod1
to
.BR Mod5 ,
or
.B Alt
(equivalent to
.BR Mod1 ),
or
.B Super
(equivalent to
.BR Mod4 );
and
.I button
is the number of a mouse button.
When this option is used,
.B pmenu
listens to button presses on the root window,
and shows the pie menu when the given button is pressed,
together with the given modifier,
on the root window.
For example, invoking
.B pmenu
with the option
.B -x Super-3
makes a menu open when clicking with the third mouse button on the root window,
or when clicking with the third mouse button together with the Super (Mod4) modifier on any window.
This option makes
.B pmenu
run continuously;
so it should be used when
.B pmenu
is invoked in background on a X startup file (like
.BR "~/.xinitrc" ).
.TP
\fB\-X\fP [\fImod\fP-]\fIbutton\fP
Just like
.BR \-x ,
but also pass the click to the root window
(for the window manager to use it, for example).
This option is incompatible with
.BR \-x .
.PP
Each item read from stdin has the following format:
.IP
.EX
ITEM := [TABS] [IMAGE TABS] LABEL [TABS OUTPUT] NEWLINE
.EE
.PP
That means that each item is composed by tabs,
followed by an image specification, followed by more tabs and a label,
followed by more tabs and an output, and ended by a newline.
Brackets group optional elements.
.IP
The initial tabs indicate the menu hierarchy:
items indented with a tab are shown in a submenu of the preceding item not indented.
An item without initial tabs is a top-level item.
.IP
The image is a string of the form "IMG:/path/to/image.png".
It specifies the path to a image file to be shown as icon in the slice.
If the path does not begin with "/", "./" or "../", the file is searched
on the paths specified in the
.B ICONPATH
environment variable.
.IP
The label is the string that will be shown as an item in the menu.
If the item includes a icon, then no label is shown on the menu;
however, a tooltip with the label pops up when hovering the icon.
.IP
The output is the string that will be output after selecting the item.
If an item does not have an output, its label is used as its output.
If the output begins with the $ character, then this string represents a command
that will be run by
.B pmenu
using 
.IR popen (3)
and whose output will be used to generate a submenu.
.IP
The newline terminates the item specification.
.SH USAGE
.B pmenu
is controlled by the mouse,
but can also be controlled by the keyboard.
Pie slices can be selected using
Tab (with and without Shift),
Enter and Esc.
.TP
.BR Tab
Cycle through the slices in the clockwise direction.
.TP
.BR Shift-Tab
Cycle through the items in the anticlockwise direction.
.TP
.BR Enter
Select the highlighted item.
.TP
.B Esc
Go to the menu above or exit pmenu.
.SH RESOURCES
.B
pmenu
understands the following X resources.
.TP
.B pmenu.font
The font in which the labels should be drawn.
.TP
.B pmenu.background
The background color of non-selected slices in the menu.
.TP
.B pmenu.foreground
The color of the label text of non-selected slices in the menu.
.TP
.B pmenu.selbackground
The background color of selected slices in the menu.
.TP
.B pmenu.selforeground
The color of the label text of selected slices in the menu.
.TP
.B pmenu.border
The color of the border around the menu.
.TP
.B pmenu.separator
The color of the separator between slices in the menu.
.TP
.B pmenu.borderWidth
The size in pixels of the border around the menu.
.TP
.B pmenu.separatorWidth
The size in pixels of the slice separator.
.TP
.B pmenu.diameterWidth
The size in pixels of the pie menu.
.SH ENVIRONMENT
The following environment variables affect the execution of
.BR pmenu .
.TP
.B DISPLAY
The display to start
.B pmenu
on.
.TP
.B ICONPATH
A colon-separated list of directories used to search for the location of image files.
.SH EXAMPLES
The following script illustrates the use of
.BR pmenu .
The output is redirected to
.IR sh (1),
creating a command to be run by the shell.
.IP
.EX
#!/bin/sh

<<EOF pmenu | sh &
Apps
	Firefox	firefox
	Chrome	chromium
	Vivaldi	vivaldi
	Gimp	gimp
Terms
	xterm	xterm
	urxvt	urxvt
	st	st
Halt	poweroff
Reboot	reboot
EOF
.EE
.PP
For example, by selecting \(lqApps\(rq, a new menu will appear.
Selecting \(lqFirefox\(rq in the new menu opens firefox.
.SH SEE ALSO
.IR xmenu (1)
